ECsite/ECsite/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('useraccount.urls')),
    path('defo_store/', include('defo_store.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ECsite/defo_store/urls.py
from django.urls import path
from . import views

app_name = 'defo_store'
urlpatterns = [
    path('chemical_list/', views.ChemicalListView.as_view(), name='chemical_list'),
]

ECsite/useraccount/urls.py
from django.urls import path
from . import views

app_name = 'useraccount'

urlpatterns = [
    path('top/',views.TopView.as_view(),name='top' ),
    path('registration/',views.RegistrationView.as_view(),name='registration' ),
    path('login/',views.MyLoginView.as_view(),name='login' ),
    path('logout/',views.MyLogoutView.as_view(),name='logout' ),
    path('user/',views.MyUserView.as_view(),name='user' ),
]

ECsite/defo_store/models.py
from django.db import models

class ChemicalTypes(models.Model):
    name = models.CharField(max_length=300)
    
    class Meta:
        db_table = 'chemical_types'
    
    def __str__(self):
        return self.name


class Manufactures(models.Model):
    name = models.CharField(max_length=300)
    
    class Meta:
        db_table = 'manufactures'
    
    def __str__(self):
        return self.name


class Chemicals(models.Model):
    name = models.CharField(max_length=300)
    cas = models.CharField(max_length=300)
    price = models.IntegerField()
    stock = models.IntegerField()
    chemical_type = models.ForeignKey(
        ChemicalTypes,on_delete=models.CASCADE
    )
    manufacture = models.ForeignKey(
        Manufactures,on_delete=models.CASCADE,
    )
    
    class Meta:
        db_table = 'chemicals'
    
    def __str__(self):
        return self.name


class ChemicalPictures(models.Model):
    picture = models.FileField(upload_to='chemical_pictures/')
    chemical = models.ForeignKey(
        Chemicals,on_delete=models.CASCADE
    )
    order = models.IntegerField()

    class Meta:
        db_table = 'chemical_pictures'
        ordering = ['order']
    
    def __str__(self):
        return self.chemical.name + ':' + str(self.order)

ECsite/useraccount/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)
from django.urls import reverse_lazy

class UserManager(BaseUserManager):
    def create_user(self, email, date_of_birth, password=None):
        if not email:
            raise ValueError('You need Email address!')
        user = self.model(
            email = email,
            date_of_birth = date_of_birth,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self,email,date_of_birth,password=None):
        user = self.model(
            email = email,
            date_of_birth = date_of_birth,
        )
        user.set_password(password)
        user.is_staff = True
        user.is_active = True
        user.is_superuser = True
        user.save(using=self.db)
        return user


class MyUser(AbstractBaseUser,PermissionsMixin):
    username = models.CharField(max_length=100)
    email = models.EmailField(max_length=100,unique=True)
    date_of_birth = models.DateField()
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['date_of_birth']
    
    objects = UserManager()
    
    def get_absolute_url(self):
        return reverse_lazy('useraccount:top')

ECsite/useraccount/forms.py
from django import forms
from .models import MyUser
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.forms import AuthenticationForm

class RegistrationForm(forms.ModelForm):
    username = forms.CharField(label='name')
    date_of_birth = forms.DateField(label='生年月日')
    email = forms.EmailField(label='Email')
    password = forms.CharField(label='パスワード')
    
    class Meta():
        model = MyUser
        fields =['username','date_of_birth','email','password']
    
    def save(self, commit=False):
        user = super().save(commit=False)
        validate_password(self.cleaned_data['password'],user)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user
    


class LoginForm(AuthenticationForm):
    email = forms.EmailField(label='Email address')
    password = forms.CharField(label='password', widget=forms.PasswordInput())
    remenber = forms.BooleanField(label='keep login', required=False)

# もう一つのログイン実装
# class LoginForm(forms.Form):
#     email = forms.EmailField(label='Email address')
#     password = forms.CharField(label='password', widget=forms.PasswordInput())

ECsite/defo_store/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

import os
from .models import(
    Chemicals,
)

class ChemicalListView(LoginRequiredMixin,ListView):
    model = Chemicals
    template_name = os.path.join('defo_store','chemical_list.html')
    
    # リストの絞り込み機能
    def get_queryset(self):
        query = super().get_queryset()
        chemical_type = self.request.GET.get('chemical_type',None)
        chemical_name = self.request.GET.get('chemical_name',None)
        chemical_cas = self.request.GET.get('chemical_cas',None)
        if chemical_type:
            query = query.filter(
                #__nameでChemicalTypeのnameフィールドを指定
                chemical_type__name=chemical_type,
            )
        if chemical_name:
            query = query.filter(
                name=chemical_name,
            )
        if chemical_cas:
            query = query.filter(
                cas=chemical_cas,
            )
        return query
    
    # 絞り込み機能のフォームが検索後に空になるのを防ぐ
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['chemical_type'] = self.request.GET.get('chemical_type','')
        context['chemical_name'] = self.request.GET.get('chemical_name','')
        context['chemical_cas'] = self.request.GET.get('chemical_cas','')
        return context

ECsite/useraccount/views.py
from django.shortcuts import render,redirect
from django.views.generic.edit import CreateView,FormView
from django.views.generic.base import TemplateView,View
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView,LogoutView
from .forms import RegistrationForm, LoginForm

class TopView(TemplateView):
    template_name = 'top.html'
    

class RegistrationView(CreateView):
    template_name = 'registration.html'
    form_class = RegistrationForm


class MyLoginView(LoginView):
    template_name = 'login.html'
    authentication_form = LoginForm
    
    #ログイン維持するかのチェックボックス追加
    def form_valid(self,form):
        remember = form.cleaned_data['remember']
        if remember:
            self.request.session.set_expiry(1000000)
        return super.form_valid(form)
    

class MyLogoutView(LogoutView):
    pass

#もう一つのログイン実装方法
# class MyLoginView(FormView):
#     template_name = 'login.html'
#     form_class = LoginForm
    
#     def post(self, request, *args, **kwargs):
#         email = request.POST['email']
#         password = request.POST['password']
#         user = authenticate(email=email, password = password)
#         next_url = request.POST['next']
#         if user is not None and user.is_active:
#             login(request,user)
            
#         #ユーザーページ->ログイン画面と遷移していたときトップに戻さず直接ユーザーページに飛ばしてあげる
#         if next_url:
#             return redirect(next_url)
#         return redirect('useraccount:top')

# class MyLogoutView(View):
    
#     def get(self, request, *args, **kwargs):
#         logout(request)
#         return redirect('useraccount:login')
    

class MyUserView(TemplateView):
    template_name = 'user.html'
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

ECsite/templates/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <title></title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Fifth navbar example">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'useraccount:top' %}">&nbsp;Top</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
        
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'useraccount:logout' %}">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'defo_store:chemical_list' %}">Chemical List</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'useraccount:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'useraccount:registration' %}">Registration</a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'useraccount:user' %}">User Page</a>
                        </li>
                    </ul>
                </div>
            </div>
          </nav>
        {% block contents %}
        {% endblock contents %}

        <footer class="footer mt-auto py-3 bg-light">
            <div class="container">
            </div>
        </footer>
    </body>
</html>

ECsite/templates/defo_store/chemical_list.html
{% extends 'base.html' %}
{% block contents %}
<div class="col-10 offset-1">
    <h2>chemical list</h2>
    <div class="container">
    <div class="row justify-content-start">
    <form method="GET" action="{% url 'defo_store:chemical_list' %}">
        <div class="col"><p>Chemical Type: <input type="text" name="chemical_type" value="{{ chemical_type }}"/></p></div>
        <div class="col"><p>Chemical Name: <input type="text" name="chemical_name" value="{{ chemical_name }}"/></p></div>
        <div class="col"><p>Cas No.: <input type="text" name="chemical_cas" value="{{ chemical_cas }}"/></p></div>
        <div class="col"><p><input type="submit" value="Perform"/></p></div>
    </form>
    </div>
</div>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <td>TYPE</td>
                <td>Chemical Name</td>
                <td>CAS No.</td>
                <td>Price</td>
                <td>Stock Amount</td>
                <td>Manufacture</td>
            </tr>
        </thead>
        <tbody>
            {% for chemical in object_list %}
            <tr>
                <td>{{ chemical.chemical_type.name }}</td>
                <td>{{ chemical.name }}</td>
                <td>{{ chemical.cas }}</td>
                <td>{{ chemical.price }}</td>
                <td>{{ chemical.stock }}</td>
                <td>{{ chemical.manufacture.name }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock contents %}

ECsite/templates/login.html
{% extends 'base.html' %}
{% block contents %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="next" value="{{ request.GET.next }}">
    <input type="submit" value="login">
</form>
{% endblock contents %}

ECsite/templates/registration.html
{% extends 'base.html' %}
{% block contents %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Registration">
{% endblock contents %}

ECsite/templates/top.html
{% extends 'base.html' %}
{% block contents %}
<h2><p>&nbsp;Hello</p></h2>
<h2><p>&nbsp;This is Top Page!</p></h2>
{% endblock contents %}

ECsite/templates/user.html
{% extends 'base.html' %}
{% block contents %}
<h2><p>&nbsp;Hello</p></h2>
<h2><p>&nbsp;This is {{ user.username }}'s Page!</p></h2>
{% endblock contents %}